# Generated by Django 3.0.4 on 2020-04-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=400)),
                ('Category', models.CharField(choices=[('Студент', 'student'), ('Школьник', 'School'), ('Пенсионер', 'retiree'), ('Работаю', 'worked')], max_length=400)),
                ('Purpose', models.CharField(choices=[('Просто так', 'Simply'), ('Экономия', 'Economy'), ('Сбережение', 'Saving')], max_length=400)),
                ('Password', models.CharField(max_length=400)),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
